// Source: src/App.civet
// Generated by Civetman

export function App(){
    return <div>
        <h1>
            {`Hello`}
        </h1>
    </div>
}
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidW5rbm93bi50c3giLCJzb3VyY2VzIjpbInVua25vd24iXSwibWFwcGluZ3MiOiJBQUFBLE1BQU0sQ0FBQyxRQUFRLENBQUMsR0FBRyxDQUFDLENBQUMsQ0FBQztBQUN0QixBQUFBLElBQUksTUFBTSxDLEMsRyxDQUFNO0FBQ2hCLEFBQUEsUSxDLEUsQ0FBWTtBQUNaLEFBQUEsWUFBWSxDQUFDLENBQUMsS0FBSyxDQUFDLEM7USxFLEUsQztJLEUsRyxDQUFDO0FBQ3JCLEFBQUEiLCJuYW1lcyI6W10sInNvdXJjZXNDb250ZW50IjpbImV4cG9ydCBmdW5jdGlvbiBBcHAoKXtcbiAgICByZXR1cm4gPGRpdj5cbiAgICAgICAgPGgxPlxuICAgICAgICAgICAge2BIZWxsb2B9XG59Il19